name: Help
description: Ask for help or report a bug with thing
title: "[ISSUE] <title>"
labels: [Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Game**: Minecraft 1.18.2
        - **Injector**: 1.0.0
        - **thing**: 0.0.0
        - ****: 1.3.0
        - **server**: 1.3.4
    value: |
        - Game:
        - Injector:
        - thing:
        - :
        - server:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Logs (optional, can be found by clicking Logs button at bottom left of Injector GUI)
    description: |
      The contents of the thing log file. Note: you may need to redact your Windows username or any server IPs you have connected to
  validations:
    required: false
